2021-12-13 15:13:54.998701: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/xilinx/xrt/lib:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib:/opt/vitis_ai/conda/envs/vitis-ai-tensorflow/lib
2021-12-13 15:13:54.998737: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

------------------------------------
TensorFlow version :  2.3.0
3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:53) 
[GCC 9.4.0]
------------------------------------
Command line options:
 --float_model  :  float_model.h5
 --quant_model  :  quantized_model.h5
 --batchsize    :  20
 --tfrec_dir    :  build/tfrecords
 --evaluate     :  True
------------------------------------

Traceback (most recent call last):
  File "1.1-quantize.py", line 132, in <module>
    main()
  File "1.1-quantize.py", line 128, in main
    quant_model(args.float_model, args.quant_model, args.batchsize, args.tfrec_dir, args.evaluate)
  File "1.1-quantize.py", line 58, in quant_model
    os.makedirs(head_tail[0], exist_ok = True)
  File "/opt/vitis_ai/conda/envs/vitis-ai-tensorflow2/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
